// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_b3OfLBvtq",
    "aws_user_pools_web_client_id": "1oi0n19n3llf0n0m78b6f23tlt",
    "aws_appsync_graphqlEndpoint": "https://6zbzbtjtu5dpvawhq5zv3xdipa.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
